config/routes.rb
ClJr::Application.routes.draw do

  root to: 'categories#index'
  resources :categories, :except => [:index, :edit, :update, :destroy]
  resources :posts

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :name, :price, :body, :email, :category_id
  belongs_to :category

  before_create :generate_key

  def generate_key
  	random_key = ((0..9).to_a.sample(3) + ('A'..'Z').to_a.sample(7)).shuffle.join
  	self.key = random_key
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
        p '**************'
    p params
    p flash
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    p params
    @category = Category.new params[:category]
    redirect_to categories_path if @category.save
  end

  def show
    @category = Category.find params[:id]
    @posts = @category.posts
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post]
    redirect_to post_path(@post.id) if @post.save
  end

  def show
    @post = Post.find params[:id]
    @category = @post.category
  end

  def edit
    @post = Post.find params[:id]
    redirect_to root_path unless @post.key == params[:key]
  end

  def update
    @post = Post.find params[:id]
    @post.update_attributes params[:post]
    redirect_to post_path(@post.id) if @post.save
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to :root, :notice => "Post Deleted."
  end   

end

app/helpers/application_helper.rb
module ApplicationHelper
  def all_categories
    Category.all
  end
end

app/views/categories/index.html.erb
<h1>Welcome To the FUCKIN CATEGORIES</h1>


<% @categories.each do |category| %>
  <p><%= link_to category.title, category_path(category.id) %></p>
<% end %>

app/views/categories/new.html.erb
<h1>Create a Category!!!</h1>

<%= form_for @category do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Sell it" %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>
<h3>These are the postings:</h3>

<p><%= render "layouts/posts" %></p>
<p><%= link_to 'Create New Post', :new_post %></p>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <%= link_to "Home", :root %>
  <%= link_to "New Category", :new_category %>
  <%= link_to "All Posts", :posts %>
  <%= link_to "New Post", :new_post %>
</div>

app/views/layouts/_posts.html.erb
<div class="posts">
  <ul>
    <% @posts.each do |post| %>
    <li><%= link_to post.name, post_path(post.id) %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClJr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>
<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit <%= @post.name %></h1>

<%= form_for @post do |f| %>
<p>Category: <%= f.select :category_id, options_for_select( all_categories.map{|category| ["#{category.title}", category.id] }, @post.category.id  ) %></p>
<p><%= f.text_field :name, :placeholder => @post.name %> Name</p>
<p><%= f.text_field :price, :placeholder => @post.price %> Description</p>
<p><%= f.text_area :body, :placeholder => @post.body %> Body</p>
<p><%= f.text_field :email, :placeholder => @post.email %> Email</p>
<%= f.submit "Submit Update" %> or <%= link_to "Delete Post", post_path, :method => :delete %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<p><%= render "layouts/posts" %></p>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= form_for @post do |f| %>
<p>Category: <%= f.select :category_id, options_for_select( all_categories.map{|category| ["#{category.title}", category.id] } ) %></p>
<p><%= f.text_field :name, :placeholder => 'Name' %></p>
<p><%= f.text_field :price, :placeholder => 'Price $' %></p>
<p><%= f.text_area :body, :placeholder => 'Description' %></p>
<p><%= f.email_field :email, :placeholder => 'Email' %></p>

<%= f.submit "Sell it" %>
<% end %>

app/views/posts/show.html.erb
<h2>Name: <%= @post.name %></h2>
<p>Category: <%= link_to @category.title, category_path(@category.id) %></p>
<p>Price: <%= @post.price %></p>
<p>Description: <%= @post.body %></p>
<p>Contact Email: <%= mail_to @post.email %></p>

<p>Secret Key: <span id="skey">/posts/<%= @post.id %>/edit?key=<%= @post.key %></span></p>